### ISSUE TITLE
Doesn't work if imported from npm

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity-sync#7]
Hi Dave, I have a problem: when I include Flickity and flickity-sync from the CDN (like [seen here](https://codepen.io/desandro/pen/OPZJmE)), it works fine, but if I import the scripts (same versions) from my local `node_modules` (browserify, babelify,...) it fails silently:
```javascript
import Flickity from 'flickity';
import 'flickity-sync';

function initSingleSliders() {
  $(".single .single-slider").each(function(index) {

    var $slider = $(this);
    var uniqueClass = 'single-slider-'+index;
    $slider.addClass( uniqueClass );
    
    var singleSlider = new Flickity( $slider[0], {
      lazyLoad: true,
      wrapAround: true,
      pageDots: false
    });

    var $nav = $slider.next('.single-slider-nav-wrap').find('.single-slider-nav');

    var navSlider = new Flickity( $nav.get(0), {
      sync: '.' + uniqueClass,
      contain: true,
      pageDots: false,
      wrapAround: false,
      freeScroll: true
    });

  });
}
$(document).ready(initSingleSliders);

```

**Comment by hirasso** [comment]
So, I have to revoke my statement. It _does_ work with NPM. I just built a reduced test case where it works just fine. I am really puzzled...

**Comment by hirasso** [comment]
So, after a quite hard debugging session I figured it out. I had a node_modules folder containing flickity and flickity-sync higher above the folder I was working in. When I deleted these packages and reinstalled them inside the working directory, it started working again.

**Comment by desandro** [comment]
Thanks for following up!
